kind: Service
apiVersion: v1
metadata:
  name: pingpong-service
spec:
  type: LoadBalancer
  selector:
    app: pingpong
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8003